apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJTMVpCWm1GdVlYTjVaWFk2WjJsMGFIVmlYM0JoZEY4eE1VSllXRnBIVTFrd1NtVjZkbEZFYjI1U1kzYzFYekJ1TjBSbFpIaFpTVkZYT1V0YU5FTjVhM1ZWWnpjMFVtZFNiRkJyTUhGVFFrRkxaWGRRYlU5VVNuWkVSMUZJVDFORVZrVlNSa1V3WVhFMCIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
